version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OM_MODE=api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped 